//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSPEdit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\"?>\r\n<configuration displayname=\"Computer Configuration\">\r\n    " +
            "<softwareSettings displayname=\"Software Settings\" imageURL=\"~/Images/Folder_16.p" +
            "ng\"></softwareSettings>\r\n    <windowsSettings displayname=\"Windows Settings\" ima" +
            "geURL=\"~/Images/Folder_16.png\"></windowsSettings>\r\n    <administrativeTemplates " +
            "displayname=\"Administrative Templates\" imageURL=\"~/Images/Folder_16.png\">\r\n     " +
            "   <PolicyNode displayname=\"Google\" name=\"Google:Cat_Google\"></PolicyNode>\r\n    " +
            "    <PolicyNode displayname=\"Adobe Reader 2017\" name=\"Cat_Adobe_Reader_2017_31\">" +
            "</PolicyNode>\r\n        <PolicyNode displayname=\"Windows Components\" name=\"window" +
            "s:WindowsComponents\">\r\n            <PolicyNode displayname=\"Tablet PC\" name=\"win" +
            "dows:TabletPC\"></PolicyNode>\r\n            <PolicyNode displayname=\"Server\" name=" +
            "\"backup:Backup\\BackupServer\"></PolicyNode>\r\n            <PolicyNode displayname=" +
            "\"Server\" name=\"BackupServer\"></PolicyNode>\r\n            <PolicyNode displayname=" +
            "\"Server\" name=\"backup:Backup\"></PolicyNode>\r\n            <PolicyNode displayname" +
            "=\"Location And Sensors\" name=\"sensors:LocationAndSensors\"></PolicyNode>\r\n       " +
            "     <PolicyNode displayname=\"Maintenance Scheduler\" name=\"msched:MaintenanceSch" +
            "eduler\"></PolicyNode>\r\n            <PolicyNode displayname=\"File Explorer\" name=" +
            "\"windows:WindowsExplorer\"></PolicyNode>\r\n            <PolicyNode displayname=\"Da" +
            "ta Collection And Preview Builds\" name=\"windows:DataCollectionAndPreviewBuilds\">" +
            "</PolicyNode>\r\n            <PolicyNode displayname=\"Internet Explorer\" name=\"Int" +
            "ernetExplorer\">\r\n                <PolicyNode displayname=\"Application Compatibil" +
            "ity\" name=\"CategoryAppCompat\"></PolicyNode>\r\n                <PolicyNode display" +
            "name=\"Corporate Settings\" name=\"CorporateSettings\"></PolicyNode>\r\n              " +
            "  <PolicyNode displayname=\"Internet Control Panel\" name=\"InternetCPL\">\r\n        " +
            "            <PolicyNode displayname=\"Advanced Page\" name=\"AdvancedPage\"></Policy" +
            "Node>\r\n                    <PolicyNode displayname=\"Security Page\" name=\"Securit" +
            "yPage\">\r\n                        <PolicyNode displayname=\"Local Machine Zone\" na" +
            "me=\"inetres:IZ_LocalMachineZone\"></PolicyNode>\r\n                        <PolicyN" +
            "ode displayname=\"Intranet Zone\" name=\"inetres:IZ_IntranetZone\"></PolicyNode>\r\n  " +
            "                      <PolicyNode displayname=\"Trusted Sites Zone\" name=\"inetres" +
            ":IZ_TrustedSitesZone\"></PolicyNode>\r\n                        <PolicyNode display" +
            "name=\"Internet Zone\" name=\"inetres:IZ_InternetZone\"></PolicyNode>\r\n             " +
            "           <PolicyNode displayname=\"Restricted Sites Zone\" name=\"inetres:IZ_Rest" +
            "rictedSitesZone\"></PolicyNode>\r\n                        <PolicyNode displayname=" +
            "\"Locked-Down Local Machine Zone\" name=\"inetres:IZ_LocalMachineZoneLockdown\"></Po" +
            "licyNode>\r\n                        <PolicyNode displayname=\"Locked-Down Intranet" +
            " Zone\" name=\"inetres:IZ_IntranetZoneLockdown\"></PolicyNode>\r\n                   " +
            "     <PolicyNode displayname=\"Locked-Down Trusted Sites Zone\" name=\"inetres:IZ_T" +
            "rustedSitesZoneLockdown\"></PolicyNode>\r\n                        <PolicyNode disp" +
            "layname=\"Locked-Down Internet Zone\" name=\"inetres:IZ_InternetZoneLockdown\"></Pol" +
            "icyNode>\r\n                        <PolicyNode displayname=\"Locked-Down Restricte" +
            "d Sites Zone\" name=\"inetres:IZ_RestrictedSitesZoneLockdown\"></PolicyNode>\r\n     " +
            "               </PolicyNode>\r\n                    <PolicyNode displayname=\"Secur" +
            "ity Features\" name=\"secFea\">\r\n                        <PolicyNode displayname=\"N" +
            "etwork Protocol Lockdown\" name=\"IESF_CategoryNetworkProtocolLockdown\"></PolicyNo" +
            "de>\r\n                    </PolicyNode>\r\n                </PolicyNode>\r\n         " +
            "       <PolicyNode displayname=\"Internet Settings\" name=\"InternetSettings\">\r\n   " +
            "                 <PolicyNode displayname=\"Component Updates\" name=\"ComponentUpda" +
            "tes\"></PolicyNode>\r\n                    <PolicyNode displayname=\"Advanced settin" +
            "gs\" name=\"Advanced\"></PolicyNode>\r\n                </PolicyNode>\r\n            </" +
            "PolicyNode>\r\n            <PolicyNode displayname=\"Remote Desktop Services\" name=" +
            "\"rdp\">\r\n                <PolicyNode displayname=\"Remote Destop Session Host\" nam" +
            "e=\"rdp:host\">\r\n                    <PolicyNode displayname=\"Printer Redirection\"" +
            " name=\"terminalserver:TS_PRINT_REDIRECTION\"></PolicyNode>\r\n                    <" +
            "PolicyNode displayname=\"Remote Session Environment\" name=\"terminalserver:sess\">\r" +
            "\n                        <PolicyNode displayname=\"RemoteFX for Windows Server 20" +
            "08 R2\" name=\"terminalserver:TS_LEGACY_REMOTEFX\"></PolicyNode>\r\n                 " +
            "   </PolicyNode>\r\n                </PolicyNode>\r\n                <PolicyNode dis" +
            "playname=\"Remote Destop Connection Client\" name=\"terminalserver:TS_CLIENT\">\r\n   " +
            "                 <PolicyNode displayname=\"RemoteFX USB Device Redirection\" name=" +
            "\"terminalserver:TS_CLIENT\\TS_USB_REDIRECTION\"></PolicyNode>\r\n                </P" +
            "olicyNode>\r\n            </PolicyNode>\r\n            <PolicyNode displayname=\"Micr" +
            "osoft Management Console\" name=\"mmc\">\r\n                <PolicyNode displayname=\"" +
            "Restricted-Permitted Snap-ins\" name=\"mmc:MMC_RESTRICT\">\r\n                    <Po" +
            "licyNode displayname=\"Extension Snap-ins\" name=\"mmc:MMC_ExtensionSnapins\"></Poli" +
            "cyNode>\r\n                </PolicyNode>\r\n            </PolicyNode>\r\n            <" +
            "PolicyNode displayname=\"Windows Error Reporting\" name=\"error:rep\">\r\n            " +
            "    <PolicyNode displayname=\"Advanced Error Reprting Settings\" name=\"wer:CAT_Win" +
            "dowsErrorReportingAdvanced\"></PolicyNode>\r\n            </PolicyNode>\r\n        </" +
            "PolicyNode>\r\n        <PolicyNode displayname=\"System\" name=\"windows:System\">\r\n  " +
            "          <PolicyNode displayname=\"Troubleshooting and Diagnostics\" name=\"window" +
            "s:Troubleshooting\"></PolicyNode>\r\n            <PolicyNode displayname=\"Logon\" na" +
            "me=\"logon:Logon\"></PolicyNode>\r\n            <PolicyNode displayname=\"Device Inst" +
            "allation\" name=\"devinst:DeviceInstall_Category\"></PolicyNode>\r\n            <Poli" +
            "cyNode displayname=\"Driver Installation\" name=\"devinst:DriverInstall_Category\"><" +
            "/PolicyNode>\r\n            <PolicyNode displayname=\"Internet Communication Manage" +
            "ment\" name=\"windows:InternetManagement\">\r\n                <PolicyNode displaynam" +
            "e=\"Internet Communication Settings\" name=\"windows:InternetManagement_Settings\"><" +
            "/PolicyNode>\r\n            </PolicyNode>\r\n        </PolicyNode>\r\n        <PolicyN" +
            "ode displayname=\"Start Menu and Taskbar\" name=\"windows:StartMenu\"></PolicyNode>\r" +
            "\n        <PolicyNode displayname=\"ControlPanel\" name=\"windows:ControlPanel\"></Po" +
            "licyNode>\r\n        <PolicyNode displayname=\"Printers\" name=\"windows:Printers\"></" +
            "PolicyNode>\r\n        <PolicyNode displayname=\"Network\" name=\"windows:Network\">\r\n" +
            "            <PolicyNode displayname=\"Network Connections\" name=\"netcon:NetworkCo" +
            "nnections\"></PolicyNode>\r\n        </PolicyNode>\r\n        <PolicyNode displayname" +
            "=\"Desktop\" name=\"windows:Desktop\">\r\n            <PolicyNode displayname=\"Desktop" +
            "\" name=\"windows:Desktop\\Desktop\"></PolicyNode>\r\n        </PolicyNode>\r\n        <" +
            "PolicyNode displayname=\"Shared Folders\" name=\"windows:SharedFolders\"></PolicyNod" +
            "e>\r\n    </administrativeTemplates>\r\n</configuration>")]
        public string DevicePathMapping {
            get {
                return ((string)(this["DevicePathMapping"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScriptPath {
            get {
                return ((string)(this["ScriptPath"]));
            }
        }
    }
}
