//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSPEdit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\"?>\r\n<configuration displayname=\"Computer Configuration\">\r\n    " +
            "<softwareSettings displayname=\"Software Settings\" imageURL=\"~/Images/Folder_16.p" +
            "ng\"></softwareSettings>\r\n    <windowsSettings displayname=\"Windows Settings\" ima" +
            "geURL=\"~/Images/Folder_16.png\"></windowsSettings>\r\n    <administrativeTemplates " +
            "displayname=\"Administrative Templates\" imageURL=\"~/Images/Folder_16.png\">\r\n     " +
            "   <PolicyNode displayname=\"Google\" name=\"Google:Cat_Google\"></PolicyNode>\r\n    " +
            "    <PolicyNode displayname=\"Adobe Reader 2017\" name=\"Cat_Adobe_Reader_2017_31\">" +
            "</PolicyNode>\r\n        <PolicyNode displayname=\"Citrix\" name=\"citrix:CITRIX_COMP" +
            "ONENTS\"></PolicyNode>\r\n        <PolicyNode displayname=\"Foxit\" name=\"FOXIT\"></Po" +
            "licyNode>\r\n        <PolicyNode displayname=\"Windows Components\" name=\"windows:So" +
            "ftware\"></PolicyNode>\r\n        <PolicyNode displayname=\"Windows Components\" name" +
            "=\"windows:WindowsComponents\">\r\n            <PolicyNode displayname=\"Tablet PC\" n" +
            "ame=\"windows:TabletPC\"></PolicyNode>\r\n            <PolicyNode displayname=\"Serve" +
            "r\" name=\"backup:Backup\\BackupServer\"></PolicyNode>\r\n            <PolicyNode disp" +
            "layname=\"Server\" name=\"BackupServer\"></PolicyNode>\r\n            <PolicyNode disp" +
            "layname=\"Server\" name=\"backup:Backup\"></PolicyNode>\r\n            <PolicyNode dis" +
            "playname=\"Location And Sensors\" name=\"sensors:LocationAndSensors\"></PolicyNode>\r" +
            "\n            <PolicyNode displayname=\"Maintenance Scheduler\" name=\"msched:Mainte" +
            "nanceScheduler\"></PolicyNode>\r\n            <PolicyNode displayname=\"File Explore" +
            "r\" name=\"windows:WindowsExplorer\"></PolicyNode>\r\n            <PolicyNode display" +
            "name=\"Data Collection And Preview Builds\" name=\"windows:DataCollectionAndPreview" +
            "Builds\"></PolicyNode>\r\n            <PolicyNode displayname=\"Internet Explorer\" n" +
            "ame=\"InternetExplorer\">\r\n                <PolicyNode displayname=\"Application Co" +
            "mpatibility\" name=\"CategoryAppCompat\"></PolicyNode>\r\n                <PolicyNode" +
            " displayname=\"Corporate Settings\" name=\"CorporateSettings\"></PolicyNode>\r\n      " +
            "          <PolicyNode displayname=\"Internet Control Panel\" name=\"InternetCPL\">\r\n" +
            "                    <PolicyNode displayname=\"Advanced Page\" name=\"AdvancedPage\">" +
            "</PolicyNode>\r\n                    <PolicyNode displayname=\"Security Page\" name=" +
            "\"SecurityPage\">\r\n                        <PolicyNode displayname=\"Local Machine " +
            "Zone\" name=\"inetres:IZ_LocalMachineZone\"></PolicyNode>\r\n                        " +
            "<PolicyNode displayname=\"Intranet Zone\" name=\"inetres:IZ_IntranetZone\"></PolicyN" +
            "ode>\r\n                        <PolicyNode displayname=\"Trusted Sites Zone\" name=" +
            "\"inetres:IZ_TrustedSitesZone\"></PolicyNode>\r\n                        <PolicyNode" +
            " displayname=\"Internet Zone\" name=\"inetres:IZ_InternetZone\"></PolicyNode>\r\n     " +
            "                   <PolicyNode displayname=\"Restricted Sites Zone\" name=\"inetres" +
            ":IZ_RestrictedSitesZone\"></PolicyNode>\r\n                        <PolicyNode disp" +
            "layname=\"Locked-Down Local Machine Zone\" name=\"inetres:IZ_LocalMachineZoneLockdo" +
            "wn\"></PolicyNode>\r\n                        <PolicyNode displayname=\"Locked-Down " +
            "Intranet Zone\" name=\"inetres:IZ_IntranetZoneLockdown\"></PolicyNode>\r\n           " +
            "             <PolicyNode displayname=\"Locked-Down Trusted Sites Zone\" name=\"inet" +
            "res:IZ_TrustedSitesZoneLockdown\"></PolicyNode>\r\n                        <PolicyN" +
            "ode displayname=\"Locked-Down Internet Zone\" name=\"inetres:IZ_InternetZoneLockdow" +
            "n\"></PolicyNode>\r\n                        <PolicyNode displayname=\"Locked-Down R" +
            "estricted Sites Zone\" name=\"inetres:IZ_RestrictedSitesZoneLockdown\"></PolicyNode" +
            ">\r\n                    </PolicyNode>\r\n                    <PolicyNode displaynam" +
            "e=\"Security Features\" name=\"secFea\">\r\n                        <PolicyNode displa" +
            "yname=\"Network Protocol Lockdown\" name=\"IESF_CategoryNetworkProtocolLockdown\"></" +
            "PolicyNode>\r\n                    </PolicyNode>\r\n                </PolicyNode>\r\n " +
            "               <PolicyNode displayname=\"Internet Settings\" name=\"InternetSetting" +
            "s\">\r\n                    <PolicyNode displayname=\"Component Updates\" name=\"Compo" +
            "nentUpdates\"></PolicyNode>\r\n                    <PolicyNode displayname=\"Advance" +
            "d settings\" name=\"Advanced\"></PolicyNode>\r\n                </PolicyNode>\r\n      " +
            "      </PolicyNode>\r\n            <PolicyNode displayname=\"Remote Desktop Service" +
            "s\" name=\"rdp\">\r\n                <PolicyNode displayname=\"Remote Destop Session H" +
            "ost\" name=\"rdp:host\">\r\n                    <PolicyNode displayname=\"Printer Redi" +
            "rection\" name=\"terminalserver:TS_PRINT_REDIRECTION\"></PolicyNode>\r\n             " +
            "       <PolicyNode displayname=\"Remote Session Environment\" name=\"terminalserver" +
            ":sess\">\r\n                        <PolicyNode displayname=\"RemoteFX for Windows S" +
            "erver 2008 R2\" name=\"terminalserver:TS_LEGACY_REMOTEFX\"></PolicyNode>\r\n         " +
            "           </PolicyNode>\r\n                </PolicyNode>\r\n                <Policy" +
            "Node displayname=\"Remote Destop Connection Client\" name=\"terminalserver:TS_CLIEN" +
            "T\">\r\n                    <PolicyNode displayname=\"RemoteFX USB Device Redirectio" +
            "n\" name=\"terminalserver:TS_CLIENT\\TS_USB_REDIRECTION\"></PolicyNode>\r\n           " +
            "     </PolicyNode>\r\n            </PolicyNode>\r\n            <PolicyNode displayna" +
            "me=\"Microsoft Management Console\" name=\"mmc\">\r\n                <PolicyNode displ" +
            "ayname=\"Restricted-Permitted Snap-ins\" name=\"mmc:MMC_RESTRICT\">\r\n               " +
            "     <PolicyNode displayname=\"Extension Snap-ins\" name=\"mmc:MMC_ExtensionSnapins" +
            "\"></PolicyNode>\r\n                </PolicyNode>\r\n            </PolicyNode>\r\n     " +
            "       <PolicyNode displayname=\"Windows Error Reporting\" name=\"error:rep\">\r\n    " +
            "            <PolicyNode displayname=\"Advanced Error Reprting Settings\" name=\"wer" +
            ":CAT_WindowsErrorReportingAdvanced\"></PolicyNode>\r\n            </PolicyNode>\r\n  " +
            "      </PolicyNode>\r\n        <PolicyNode displayname=\"System\" name=\"windows:Syst" +
            "em\">\r\n            <PolicyNode displayname=\"Troubleshooting and Diagnostics\" name" +
            "=\"windows:Troubleshooting\"></PolicyNode>\r\n            <PolicyNode displayname=\"L" +
            "ogon\" name=\"logon:Logon\"></PolicyNode>\r\n            <PolicyNode displayname=\"Dev" +
            "ice Installation\" name=\"devinst:DeviceInstall_Category\"></PolicyNode>\r\n         " +
            "   <PolicyNode displayname=\"Driver Installation\" name=\"devinst:DriverInstall_Cat" +
            "egory\"></PolicyNode>\r\n            <PolicyNode displayname=\"Internet Communicatio" +
            "n Management\" name=\"windows:InternetManagement\">\r\n                <PolicyNode di" +
            "splayname=\"Internet Communication Settings\" name=\"windows:InternetManagement_Set" +
            "tings\"></PolicyNode>\r\n            </PolicyNode>\r\n        </PolicyNode>\r\n        " +
            "<PolicyNode displayname=\"Start Menu and Taskbar\" name=\"windows:StartMenu\"></Poli" +
            "cyNode>\r\n        <PolicyNode displayname=\"ControlPanel\" name=\"windows:ControlPan" +
            "el\"></PolicyNode>\r\n        <PolicyNode displayname=\"Printers\" name=\"windows:Prin" +
            "ters\"></PolicyNode>\r\n        <PolicyNode displayname=\"Network\" name=\"windows:Net" +
            "work\">\r\n            <PolicyNode displayname=\"Network Connections\" name=\"netcon:N" +
            "etworkConnections\"></PolicyNode>\r\n        </PolicyNode>\r\n        <PolicyNode dis" +
            "playname=\"Desktop\" name=\"windows:Desktop\">\r\n            <PolicyNode displayname=" +
            "\"Desktop\" name=\"windows:Desktop\\Desktop\"></PolicyNode>\r\n        </PolicyNode>\r\n " +
            "       <PolicyNode displayname=\"Shared Folders\" name=\"windows:SharedFolders\"></P" +
            "olicyNode>\r\n    </administrativeTemplates>\r\n</configuration>")]
        public string DevicePathMapping {
            get {
                return ((string)(this["DevicePathMapping"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScriptPath {
            get {
                return ((string)(this["ScriptPath"]));
            }
        }
    }
}
